#!/usr/bin/env python3
"""Fetch VCF Installer / SDDC Manager API data structures from developer.broadcom.com
and write js/schema.js used for JSON validation.

Usage: python3 tools/fetch_schema.py [cache_dir]
"""
import html
import json
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '.schema-cache')
APIS = {
    'vcf-installer-api': ['SddcSpec'],
    'sddc-manager-api': ['DomainCreationSpec', 'ClusterCreationSpec', 'ClusterUpdateSpec', 'NetworkPool', 'HostCommissionSpec'],
}


def strip(s):
    return html.unescape(re.sub(r'<[^>]+>', '', s)).strip()


def fetch(api, name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, f'{api}__{name}.html')
    if not os.path.exists(path):
        url = f'https://developer.broadcom.com/xapis/{api}/latest/data-structures/{name}/'
        subprocess.run(['curl', '-sS', '-L', '-o', path, url], check=True)
    with open(path) as f:
        return f.read()


def enum_from(text):
    m = re.search(r'One among:\s*([A-Za-z0-9_, ]+)', text)
    if m:
        vals = [v.strip() for v in m.group(1).split(',') if v.strip()]
        return vals or None
    return None


def parse(api, name):
    h = fetch(api, name)
    ex = re.search(r'<code class="language-json">(.*?)</code>', h, re.S)
    ex = html.unescape(ex.group(1)) if ex else ''
    fields = {}
    for blk in h.split('dp-api-schema-field-container')[1:]:
        fn = re.search(r'dp-api-schema-field-name[^>]*>(.*?)</div>', blk, re.S)
        if not fn:
            continue
        fname = strip(fn.group(1))
        tblock = re.search(r'dp-api-schema-field-type">(.*?)</div>', blk, re.S).group(1)
        refs = re.findall(r'data-structures/(\w+)/', tblock)
        spans = [strip(x) for x in re.findall(r'<span>(.*?)</span>', tblock, re.S)]
        tstr = ' '.join(spans)
        d = re.search(r'dp-api-schema-field-description[^>]*>(.*?)</div>', blk, re.S)
        desc = strip(d.group(1)) if d else ''
        f = {}
        is_array = 'array of' in tstr
        base = refs[0] if refs else next((t for t in ('string', 'integer', 'boolean', 'number', 'object') if t in tstr), 'string')
        if is_array:
            f['t'] = 'array'
            f['items'] = base
        else:
            f['t'] = base
        if 'field-required">Required' in blk:
            f['req'] = 1
        pat = re.search(r'As (\^.*|\(.*\)|[A-Za-z]+\|[A-Za-z|]+)$', tstr)
        if pat:
            p = pat.group(1)
            if re.fullmatch(r'\(?[A-Za-z0-9_]+(\|[A-Za-z0-9_]+)+\)?', p):
                f['enum'] = p.strip('()').split('|')
            elif p.startswith('^'):
                f['pattern'] = p
        if 'enum' not in f:
            m = re.search(r'"%s":\s*"(One among:[^"]*)"' % re.escape(fname), ex)
            e = enum_from(m.group(1)) if m else None
            if e:
                f['enum'] = e
        for c in re.findall(r'<span class="ml-2">(.*?)</span>', blk, re.S):
            k, _, v = strip(c).partition(':')
            k, v = k.strip(), v.strip()
            if k in ('minLength', 'maxLength', 'minimum', 'maximum'):
                try:
                    num = float(v)
                    if abs(num) < 1e15:
                        f[k] = int(num) if num.is_integer() else num
                except ValueError:
                    pass
        f['d'] = desc
        fields[fname] = f
    return fields


def crawl(api, roots):
    out = {}
    todo = list(roots)
    while todo:
        with ThreadPoolExecutor(12) as ex:
            res = dict(zip(todo, ex.map(lambda n: parse(api, n), todo)))
        out.update(res)
        todo = []
        for fields in res.values():
            for f in fields.values():
                r = f.get('items') if f['t'] == 'array' else f['t']
                if r and r[0].isupper() and r not in out and r not in todo:
                    todo.append(r)
    return out


def main():
    schema = {api: crawl(api, roots) for api, roots in APIS.items()}
    path = os.path.join(ROOT, 'js', 'schema.js')
    with open(path, 'w') as f:
        f.write('// Generated by tools/fetch_schema.py from developer.broadcom.com API reference. Do not edit.\n')
        f.write('window.VCF_SCHEMA = ')
        json.dump(schema, f, separators=(',', ':'), sort_keys=True)
        f.write(';\n')
    print(path, {k: len(v) for k, v in schema.items()})


if __name__ == '__main__':
    main()
